### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by StarDream521** [mcserversoft/documentation#13]
Hello handsome author
I want to publish the software you made to my personal blog (Wordpress program)
www.mcmap.xyz (new domain name www.mcmaps.cn)
(The site may not be opened recently and is being repaired and beautified)
Your software is free and extremely powerful. I want Chinese server owners to know
I will be free for players to download and I won’t get any benefits
And I will mark your platform and your name in the article
Hope to get your permission!

**Comment by LostAndDead** [comment]
Has been resolved over discord
