### ISSUE TITLE
Players online not displaying amount of players or player information.

### ISSUE THREAD

**Issue by nguyenab** [mcserversoft/documentation#2]
![image](https://user-images.githubusercontent.com/47406982/69504962-d60ca100-0edb-11ea-8912-fbe049f63bd6.png)

Pictured in the image, I have about 4 players online in the server. The number of players does not show.

The server config is set to online.

I am running Windows 10 Pro; MCSS v11.2.3.

Apologize if this is the incorrect place to create this issue. Thank you!

**Comment by Fiahblade** [comment]
This has indeed nothing to do with the documentation.
