### ISSUE TITLE
MCSS Running fine through web panel but regular panel does not show up on screen

### ISSUE THREAD

**Issue by Aus7o** [mcserversoft/documentation#36]
**Describe the bug**
After a few weeks of running my server smoothly, I opened the program again today but the normal panel that would pop up on launch just won't show up, no matter how many times I try to launch/restart my PC

**To Reproduce**
1. Open MCSS.exe
2. Wait for launch
That's pretty much it, I don't understand why I can't see the panel.

**Expected behavior**
Panel opens along with web panel and I'm able to access server panel/settings easily like normal.

**Screenshots**
Program is open but nothing displaying on screen: 
![image](https://user-images.githubusercontent.com/80645450/179645896-2181787e-9a8b-48de-a55f-45bcf7d21421.png)
The program is clearly running, checking for updates does nothing
![image](https://user-images.githubusercontent.com/80645450/179645934-37bd6b08-884b-4818-a70b-a276a01b19e9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - MCSS Version: 12.7.0

**Additional context**
I've tried reinstalling the program as well, nothing is working...

**Comment by Aus7o** [comment]
I couldn't get it pictured but hovering over the program on the task bar just shows a blank page, all white with nothing on it.

**Comment by Fiahblade** [comment]
@Aus7o Hello, I believe you posted this issue in the discord server and left before I could answer. The problem is still resolved correct?

**Comment by vaio2005** [comment]
@Aus7o Fixable by deleting the "/resources/window_size_config.json" file.
