### ISSUE TITLE
QuickEditMode ISSUE

### ISSUE THREAD

**Issue by MrPogostyc** [mcserversoft/documentation#39]
There is an Issue with the integration of the Command Prompt into the software. This problem I have identified to be caused by Windows 10's "Quick Edit Mode" under the defaults section when you right click the title bar of the Command Prompt. The issue is as follows:
The console "freezes" until prompted with a command by the user. The server works great and isn't actually frozen, however certain actions, such as closing the server, freeze before completing, and the program's kill interval is the only way I have found to get the server to close in the background without requiring me to type a one letter input into the console. I believe this is an issue for not just automation, but also backups. I have the scheduler set up to back up, but it hasn't been able to complete the job since the server freezes at "Server closing..." and requires human input to finish the task. 

This goes without saying, but just for better communication, My issue here is that this "bug" or whatever, defeats the purpose of automated scheduled tasks, such as the scheduled restart, as it cant do it whilst I'm away, as it requires human input to close properly.

The issue on its own, outside of MCSS is fixed by turning off this "QuickEditMode" in the command prompt. However, the integrated console on MCSS does not include this feature, which defeats the option to have total automated restarts.

**Describe the solution you'd like**
I'd like for an update to the software that includes the ability to check off this "QuickEditMode" under the default section as would appear in the command prompt normally if I had just normally ran my batch file. 

**Describe alternatives you've considered**
Of course, I could just run the batch file normally, but that would defeat the entire purpose of using this Software. I want to be able to schedule tasks and have remote control so when I away from home, So this isn't an option in this given context. 

**Additional context**
![image](https://user-images.githubusercontent.com/59030023/213249360-0804287b-72ab-40c5-afc2-b2b9837e5c82.png)
![image](https://user-images.githubusercontent.com/59030023/213249429-188f1dc6-8eaa-4f1f-a37d-5162012612a5.png)
![image](https://user-images.githubusercontent.com/59030023/213249496-190e74c1-4592-4acd-ace2-f71d7eabedcc.png)
Above is the described process of disabling QuickEditMode inside of Command Prompt. 

Below is a thread describing the problem and identifying the solution:
https://www.minecraftforum.net/forums/support/server-support-and/3017626-a-solution-to-minecraft-server-console-freezing

**Comment by PouletteMC** [comment]
Sounds very in-depth and more complicated than I can understand, but more suited fo either [the issue tracker](https://github.com/mcserversoft/IssueTracker) or [the discord](https://discord.gg/DEn89PB)

**Comment by MrPogostyc** [comment]
Apologies for posting this issue here. I will be sure to check that out, and move the Issue to the Issue Tracker.
